# sonar-project.properties
sonar.projectKey=students-app
sonar.projectName=Students App
sonar.projectVersion=1.0

# Source code folder
sonar.sources=.

# Language
sonar.language=py

# Encoding
sonar.sourceEncoding=UTF-8
